name: Run Tests on Pull Request to Main

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
      - uses: actions/checkout@v3

      - name: Install Node.js 20.12.2
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y node.js
          node -v
          npm -v

      - name: Install dependencies
      - run: npm ci

      - name: Run tests
        run: npm test
